Repository aeternity/aesophia, pull requests merged in 2020-03, with the labels that each got.

#239 Added documentation
  README.md
  docs/sophia.md
  docs/sophia_stdlib.md
  priv/stdlib/Frac.aes
Labels: documentation, enhancement

#247 Handle negative numbers in aci
  CHANGELOG.md
  src/aeso_aci.erl
Labels: enhancement

#253 Enchanted Frac library a bit
  priv/stdlib/Frac.aes
Labels: effort: trivial, enhancement

#249 Fixed example
  docs/sophia.md
Labels: bug
